/// API endpoints for live predictions.
abstract final class ApiConfig {
  /// Cardiogenic shock escalation API (MCS + VA-ECMO models).
  static const shockApiBaseUrl = 'http://127.0.0.1:8000';

  /// When true, loads seed JSON then refreshes MCS/ECMO from [shockApiBaseUrl]
  /// using full parquet-backed feature rows (/predict/cohort).
  static const useShockEscalationApi = false;

  /// Full patient list from aggregator backend (optional, separate port).
  static const useLiveApi = false;
  static const baseUrl = 'http://localhost:8001';

  /// When true, loads real patient predictions from assets/dashboard_results.json
  /// (generated by generate_dashboard_json.py).  Takes priority over seed JSON.
  static const useDashboardJson = true;

  /// Max patients to load per demo hospital from dashboard_results.json.
  /// Patients are ranked by mortality risk (highest first).
  static const dashboardPatientsPerHospital = 50;
}
